# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# SPU layer configuration
DISTRO_FEATURES:append = " x11 opengl"
DISTRO_FEATURES:remove = " wayland"
SPU_USER ?= "spu-user"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "meta-spu"
BBFILE_PATTERN_meta-spu = "^${LAYERDIR}/"
BBFILE_PRIORITY_meta-spu = "6"

# Ensure this layer's Cython recipe is selected for target and extended variants.
# important for PyAV which requires Cython 0.29.36 to build with FFmpeg 4.4.3 see
# https://github.com/PyAV-Org/PyAV/issues/1140
PREFERRED_VERSION_python3-cython = "2.29.36"
PREFERRED_VERSION_python3-cython-native = "2.29.36"
PREFERRED_VERSION_nativesdk-python3-cython = "2.29.36"

LAYERDEPENDS_meta-spu = "core"
LAYERVERSION_meta-spu = "1"

LAYERSERIES_COMPAT_meta-spu = "scarthgap"
