# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# SPU layer configuration
DISTRO_FEATURES:append = " x11 opengl webengine dbus"
DISTRO_FEATURES:remove = " wayland ptest"

MACHINE_FEATURES:append = " wifi touchscreen"
SPLASH = "plymouth"

SPU_USER ?= "spu-user"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "meta-spu"
BBFILE_PATTERN_meta-spu = "^${LAYERDIR}/"
BBFILE_PRIORITY_meta-spu = "100"


LAYERDEPENDS_meta-spu = "core"
LAYERVERSION_meta-spu = "1"

LAYERSERIES_COMPAT_meta-spu = "scarthgap"
