BBPATH .= ":${LAYERDIR}"
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "spu"
BBFILE_PATTERN_spu = "^${LAYERDIR}/"
BBFILE_PRIORITY_spu = "7"

# scarthgap compatibility for this layer.
LAYERSERIES_COMPAT_spu = "scarthgap"

# This layer depends on oe-core metadata.
LAYERDEPENDS_spu = "core"
