SPU_MENDER_UPDATE_POLL_INTERVAL_SECONDS ?= "60"
SPU_MENDER_INVENTORY_POLL_INTERVAL_SECONDS ?= "300"
SPU_MENDER_RETRY_POLL_INTERVAL_SECONDS ?= "30"

MENDER_UPDATE_POLL_INTERVAL_SECONDS:mender-update-install = "${SPU_MENDER_UPDATE_POLL_INTERVAL_SECONDS}"
MENDER_INVENTORY_POLL_INTERVAL_SECONDS:mender-update-install = "${SPU_MENDER_INVENTORY_POLL_INTERVAL_SECONDS}"
MENDER_RETRY_POLL_INTERVAL_SECONDS:mender-update-install = "${SPU_MENDER_RETRY_POLL_INTERVAL_SECONDS}"
